frame_camera: pylon_camera
frame_lidar:  ouster1/os1_lidar

translation_m:    [-0.049, -0.176, -0.371]         
quaternion_xyzw:  [ 0.519,  0.498, -0.485,  0.498]  

rotation_matrix:
  - [ 0.034,  0.999, -0.009]
  - [ 0.034, -0.010, -0.999]
  - [-0.999,  0.034, -0.034]

