version: '3.8'

services:
  base:
    network_mode: host
    security_opt:
      - no-new-privileges:false
    build:
      dockerfile: ws/.devcontainer/Dockerfile
      args:
        USERNAME: ${USERNAME}
        ROS_DISTRO: ${ROS_DISTRO}
    volumes:
      - ./ws/data/kitti/velodyne:/data/kitti/velodyne
      - .:/home/${USERNAME}/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/home/${USERNAME}/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_GRAPHICSSYSTEM=native
    stdin_open: true
    tty: true