<?xml version="1.0"?>
<package format="3">
  <name>kitti_writer</name>
  <version>0.0.1</version>
  <description>Convert PointCloud2 to KITTI (.bin) in real-time, optional republish.</description>

  <maintainer email="you@example.com">You</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_sensor_msgs</depend>

  <!-- Для итераторов по PointCloud2 -->
  <depend>rosidl_default_runtime</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
